/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 hoodie.glb -T -S -t
Author: deymar (https://sketchfab.com/deymar)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/this-is-a-low-poly-hoodie-ffd9ca805e624730aae1fcae790f9769
Title: this is a low-poly hoodie
*/

import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    defaultMaterial: THREE.Mesh
  }
  materials: {
    pulover: THREE.MeshStandardMaterial
  }
}

export default function Hoodie(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/hoodie-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.defaultMaterial.geometry} material={materials.pulover} scale={1} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/hoodie-transformed.glb')
