/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 rocks.glb -T -S -t
Author: carlosbarrera_10 (https://sketchfab.com/carlosbarrera_10)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/stylized-rocks-92997819b67d47c6bc8d3363e8f45e6b
Title: Stylized Rocks
*/

import * as THREE from "three";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Low_Low_0: THREE.Mesh;
  };
  materials: {
    material: THREE.MeshStandardMaterial;
  };
};

export default function Rocks(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/rocks-transformed.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Low_Low_0.geometry} material-color={"#888888"} material={materials.material} />
    </group>
  );
}

useGLTF.preload("/rocks-transformed.glb");
